export const COMMENT_ACTIONS = {
  COMMENT_ACTIONS_ADD_COMMENT: 'COMMENT_ACTIONS_ADD_COMMENT',
  COMMENT_ACTIONS_SHOW_ADD_COMMENT: 'COMMENT_ACTIONS_SHOW_ADD_COMMENT',
  COMMENT_ACTIONS_SAVE_COMMENT: 'COMMENT_ACTIONS_SAVE_COMMENT',
  COMMENT_ACTIONS_DELETE_COMMENT: 'COMMENT_ACTIONS_DELETE_COMMENT',
  COMMENT_ACTIONS_GET_COMMENTS: 'COMMENT_ACTIONS_GET_COMMENTS'
}
