export const COMMENT_ACTIONS = {
  COMMENT_ACTIONS_ADD_COMMENT: 'COMMENT_ACTIONS_ADD_COMMENT',
  COMMENT_ACTIONS_ADD_COMMENT_OK: 'COMMENT_ACTIONS_ADD_COMMENT_OK',
  COMMENT_ACTIONS_ADD_COMMENT_NO: 'COMMENT_ACTIONS_ADD_COMMENT_NO'

}
